package ru.rerumu.lists.services;

public enum MetricType {
    DB_QUERY_EXECUTION_TIME,
    DB_QUERY__SERIES_MAPPER__GET_ALL__EXECUTION_TIME,
    SERIES_CONTROLLER__GET_ALL__EXECUTION_TIME,
    SERIES_SERVICE__GET_ALL__EXECUTION_TIME,
    SERIES_BOOK_MAPPER__FIND_BY_SERIES__EXECUTION_TIME,
    SERIES_BOOK_REPOSITORY__GET_BY_SERIES__EXECUTION_TIME,
    SERIES_ENRICHMENT__EXECUTION_TIME,
    SERIES_ENRICHMENT__ONE_LOOP__EXECUTION_TIME
}
