# Default values for lists-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ""
  tag: ""
  
env:
  db:
    url: ""
    username: ""
    password: ""
  jwt_secret: ""
