apiVersion: v1
kind: Service
metadata:
  name: lists-backend-java
  labels:
    app: lists-backend-java
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: lists-backend-java0
    - port: 9090
      targetPort: 9090
      name: lists-backend-management
  selector:
    app: lists-backend-java     
